#!/usr/bin/env ruby
# frozen_string_literal: true

require 'capybara'
require 'capybara/dsl'
require 'webdrivers'

raise 'TIIME_USER environment variable is missing' if ENV['TIIME_USER'].nil?
raise 'TIIME_PASSWORD environment variable is missing' if ENV['TIIME_PASSWORD'].nil?

class Browser
  include Capybara::DSL

  def initialize
    Capybara.configure do |config|
      config.run_server = false
    end

    Capybara.current_driver = :selenium
  end
end

b = Browser.new
b.visit 'https://apps.tiime.fr'
b.fill_in 'Adresse mail', with: ENV['TIIME_USER']
b.fill_in 'Mot de passe', with: ENV['TIIME_PASSWORD']
b.click_on 'Je me connecte'

b.find('.todo', text: 'A faire', wait: 30)
token = b.execute_script 'return localStorage.getItem("access_token");'

puts "TIIME_TOKEN=#{token}"
